name               = "productsense-ingest"
main               = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding       = "DB"
database_name = "productsense_db"
database_id   = "4416b801-85d4-4314-b553-c92bee17b877"

[ai]
binding = "AI"

[[vectorize]]
binding    = "VECTORIZE"
index_name = "productsense-embeddings"

[[workflows]]
binding    = "ENRICHMENT_WORKFLOW"
name       = "productsense-enrichment"
class_name = "EnrichmentWorkflow"
